# These are supported funding model platforms

github: ['Blitheness']
custom: ['https://shirecraft.us/donate','https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=theshireserver%40gmail%2ecom&lc=US&item_name=The%20Shire%20Server&item_number=minecraft&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted']
